import { AlertTriangle, BookOpen, CalendarDays, Database, FlaskConical, Server } from "lucide-react";

function formatUpdated(value) {
  if (!value) return "Bundled build metadata";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Update time unavailable" : date.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
}

export function DatasetStatus({ metadata, recordCount }) {
  if (!metadata) return null;
  const fallback = metadata.source === "fallback";
  return (
    <section className={`dataset-status ${fallback ? "is-fallback" : ""}`} aria-label="Dataset provenance">
      {fallback && <div className="fallback-warning" role="alert"><AlertTriangle size={17} aria-hidden="true" /><span><strong>Local fallback active.</strong> The API is unavailable or returned invalid data; bundled CSV data is being shown.</span></div>}
      <div className="dataset-status-grid">
        <div className="dataset-status-item"><CalendarDays aria-hidden="true" /><span>Analysis year<strong>{metadata.selectedYear ?? metadata.latestYear}</strong></span></div>
        <div className="dataset-status-item"><Database aria-hidden="true" /><span>Data source<strong>{fallback ? "Bundled local CSV" : "AquaLink API"}</strong></span></div>
        <div className="dataset-status-item"><Server aria-hidden="true" /><span>Last updated<strong>{formatUpdated(metadata.lastUpdated)}</strong></span></div>
        <div className="dataset-status-item"><BookOpen aria-hidden="true" /><span>Score version<strong>{metadata.scoringVersion || "Not reported"}</strong></span></div>
        {Number.isFinite(recordCount) && <div className="dataset-status-item"><Database aria-hidden="true" /><span>Records in view<strong>{recordCount.toLocaleString()}</strong></span></div>}
        <span className={`prototype-badge ${metadata.synthetic ? "is-prototype" : "is-reported"}`}>
          <FlaskConical aria-hidden="true" />{metadata.synthetic ? "Prototype demonstration data" : "Reported source data"}
        </span>
      </div>
    </section>
  );
}

export function MethodologyPanel({ metadata }) {
  if (!metadata) return null;
  const thresholds = metadata.riskThresholds;
  return (
    <details className="methodology-panel">
      <summary><BookOpen size={18} aria-hidden="true" /><span>Methodology, limitations and sources</span></summary>
      <div className="methodology-content">
        <section><h2>Indicators</h2><p>Groundwater stress combines extraction stage, seasonal water-level fluctuation and historical trend. Supply-gap stress combines piped-water coverage and the shortfall from the LPCD service norm.</p></section>
        <section><h2>Scoring</h2><p>The combined 0–100 score uses 45% groundwater stress, 45% supply-gap stress and a 10% compound interaction term. A valid zero means the inputs added no stress points after clipping and weighting; it is not missing data. Recommendations are generated by the versioned backend engine.</p></section>
        {metadata.qualityMethodology ? <section><h2>Data quality and confidence</h2><p>Confidence is a rules-based quality classification, not an ML probability. The quality score weights completeness 25%, freshness 15%, source reliability 20%, observation count 15%, spatial accuracy 15%, and observed/simulated status 10%. High is 80–100, Medium is 60–79.9, and Low is below 60. Simulated records are capped at Medium confidence.</p></section> : null}
        <section><h2>Risk thresholds</h2><ul>{Object.entries(thresholds).map(([label, rule]) => <li key={label}><strong>{label}:</strong> {rule.minimum} to {rule.maximum}{rule.maximum_inclusive ? " inclusive" : " (upper bound excluded)"}</li>)}</ul></section>
        <section><h2>Sources and limitations</h2><p>This is a simulated prototype dataset for demonstrating AquaLink workflows. Values are not verified field observations and must not be used as official measurements or operational evidence. The canonical source is the AquaLink backend CSV; fallback mode uses its bundled frontend copy.</p></section>
      </div>
    </details>
  );
}

export default function DataProvenance({ metadata, recordCount }) {
  return <div className="data-transparency"><DatasetStatus metadata={metadata} recordCount={recordCount} /><MethodologyPanel metadata={metadata} /></div>;
}
